namespace FootballFantasy
{
    [default_interface]
    runtimeclass AdminRemoveFootballerPage : Microsoft.UI.Xaml.Controls.Page
    {
        AdminRemoveFootballerPage();
        Int32 MyProperty;
    }
}
