namespace FootballFantasy
{
    [default_interface]
    runtimeclass AdminRemoveFootballTeamPage : Microsoft.UI.Xaml.Controls.Page
    {
        AdminRemoveFootballTeamPage();
        Int32 MyProperty;
    }
}
